import torch
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer
from transformers import pipeline
from datasets import load_dataset
from trl import SFTConfig,SFTTrainer, DataCollatorForCompletionOnlyLM


# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

dataset = load_dataset("timdettmers/openassistant-guanaco", split="train")
print(dataset[0])

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m")

tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m")

instruction_template = "### Human:"
response_template = "### Assistant:"

collator = DataCollatorForCompletionOnlyLM(
    instruction_template=instruction_template,  
    response_template=response_template,
    tokenizer=tokenizer,
    mlm=False,
)

training_args = SFTConfig(
    output_dir="/tmp",
    num_train_epochs=10,
    save_strategy="epoch",
    fp16=False,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    max_seq_length=1024,
    do_eval=True,
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    dataset_text_field="text",
    data_collator=collator
)

# for training the model
# trainer.train()

print("\nBefore fine-tuning\n")

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=70
)

# prompted the pretrained model with a specific question
print(pipe('Can you write a short introduction about the relevance of the term "monopsony" in economics? Please use examples related to potential monopsonies in the labour market and cite relevant research.')
      [0]["generated_text"])

print("\n--------------------------------\n")

print("\nAfter fine-tuning\n")

# load the tuned model
model.load_state_dict(torch.load('Assistant_model.pt',map_location=torch.device('cpu')))

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=70
)

print(pipe('Can you write a short introduction about the relevance of the term "monopsony" in economics? Please use examples related to potential monopsonies in the labour market and cite relevant research.')
      [0]["generated_text"])